-- ==========================================================
-- FAMILY SERVICE HOURS TRACKER - SUPABASE DATABASE
-- Run this entire script in the Supabase SQL Editor.
-- ==========================================================

create extension if not exists pgcrypto;

-- -----------------------------
-- PROFILES
-- -----------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  role text not null default 'user'
    check (role in ('admin', 'user')),
  created_at timestamptz not null default now()
);

-- -----------------------------
-- SCHOOLS
-- -----------------------------
create table if not exists public.schools (
  id bigint generated by default as identity primary key,
  school_name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- -----------------------------
-- FAMILIES
-- One row represents one student/family record.
-- Family IDs may repeat across siblings, but the same
-- Family ID + student + school cannot be duplicated.
-- -----------------------------
create table if not exists public.families (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id),
  family_id text not null,
  student_name text not null,
  grade text not null,
  required_hours numeric(7,2) not null default 36
    check (required_hours >= 0),
  active boolean not null default true,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint families_unique_student
    unique (school_id, family_id, student_name)
);

-- -----------------------------
-- SERVICE ENTRIES
-- -----------------------------
create table if not exists public.service_entries (
  id uuid primary key default gen_random_uuid(),
  family_record_id bigint not null references public.families(id) on delete cascade,
  service_date date not null,
  hours numeric(7,2) not null check (hours > 0 and hours <= 36),
  activity text not null,
  notes text,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  admin_note text,
  submitted_by uuid not null,
  authorized_by uuid,
  authorized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint service_entries_submitted_by_fkey
    foreign key (submitted_by) references public.profiles(id),
  constraint service_entries_authorized_by_fkey
    foreign key (authorized_by) references public.profiles(id)
);

create index if not exists service_entries_family_idx
  on public.service_entries(family_record_id);

create index if not exists service_entries_status_idx
  on public.service_entries(status);

create index if not exists service_entries_submitted_by_idx
  on public.service_entries(submitted_by);

-- -----------------------------
-- UPDATED-AT TRIGGER
-- -----------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists families_set_updated_at on public.families;
create trigger families_set_updated_at
before update on public.families
for each row execute function public.set_updated_at();

drop trigger if exists service_entries_set_updated_at on public.service_entries;
create trigger service_entries_set_updated_at
before update on public.service_entries
for each row execute function public.set_updated_at();

-- -----------------------------
-- ROLE HELPER
-- -----------------------------
create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.profiles
  where id = auth.uid();
$$;

grant execute on function public.current_user_role() to authenticated;

-- -----------------------------
-- AUTOMATIC PROFILE CREATION
-- New accounts default to user.
-- -----------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email,''), '@', 1)),
    'user'
  )
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = coalesce(public.profiles.full_name, excluded.full_name);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Backfill profiles for accounts already created.
insert into public.profiles (id, email, full_name, role)
select
  id,
  email,
  coalesce(raw_user_meta_data ->> 'full_name', split_part(email, '@', 1)),
  case
    when lower(email) = lower('pkaraffa@bridgeportedu.net') then 'admin'
    else 'user'
  end
from auth.users
where email is not null
on conflict (id) do update
set
  email = excluded.email,
  full_name = excluded.full_name,
  role = case
    when lower(excluded.email) = lower('pkaraffa@bridgeportedu.net') then 'admin'
    else public.profiles.role
  end;

-- -----------------------------
-- ROW LEVEL SECURITY
-- -----------------------------
alter table public.profiles enable row level security;
alter table public.schools enable row level security;
alter table public.families enable row level security;
alter table public.service_entries enable row level security;

-- Profiles
drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles
for select
to authenticated
using (
  id = auth.uid()
  or public.current_user_role() = 'admin'
);

drop policy if exists "profiles_admin_update" on public.profiles;
create policy "profiles_admin_update"
on public.profiles
for update
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

-- Schools
drop policy if exists "schools_authenticated_read" on public.schools;
create policy "schools_authenticated_read"
on public.schools
for select
to authenticated
using (true);

drop policy if exists "schools_admin_manage" on public.schools;
create policy "schools_admin_manage"
on public.schools
for all
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

-- Families
drop policy if exists "families_authenticated_read" on public.families;
create policy "families_authenticated_read"
on public.families
for select
to authenticated
using (true);

drop policy if exists "families_admin_insert" on public.families;
create policy "families_admin_insert"
on public.families
for insert
to authenticated
with check (public.current_user_role() = 'admin');

drop policy if exists "families_admin_update" on public.families;
create policy "families_admin_update"
on public.families
for update
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists "families_admin_delete" on public.families;
create policy "families_admin_delete"
on public.families
for delete
to authenticated
using (public.current_user_role() = 'admin');

-- Service entries: users can read their own; admins read all.
drop policy if exists "service_entries_select_own_or_admin" on public.service_entries;
create policy "service_entries_select_own_or_admin"
on public.service_entries
for select
to authenticated
using (
  submitted_by = auth.uid()
  or public.current_user_role() = 'admin'
);

-- Users and admins may submit their own pending entries.
drop policy if exists "service_entries_insert_own" on public.service_entries;
create policy "service_entries_insert_own"
on public.service_entries
for insert
to authenticated
with check (
  submitted_by = auth.uid()
  and status = 'pending'
  and authorized_by is null
  and authorized_at is null
);

-- Only admins authorize or otherwise update entries.
drop policy if exists "service_entries_admin_update" on public.service_entries;
create policy "service_entries_admin_update"
on public.service_entries
for update
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists "service_entries_admin_delete" on public.service_entries;
create policy "service_entries_admin_delete"
on public.service_entries
for delete
to authenticated
using (public.current_user_role() = 'admin');

-- -----------------------------
-- OPTIONAL PROGRESS VIEW
-- -----------------------------
create or replace view public.family_hour_progress
with (security_invoker = true)
as
select
  f.id as family_record_id,
  f.school_id,
  s.school_name,
  f.family_id,
  f.student_name,
  f.grade,
  f.required_hours,
  coalesce(sum(se.hours) filter (where se.status = 'approved'), 0)::numeric(7,2) as approved_hours,
  coalesce(sum(se.hours) filter (where se.status = 'pending'), 0)::numeric(7,2) as pending_hours,
  greatest(
    f.required_hours - coalesce(sum(se.hours) filter (where se.status = 'approved'), 0),
    0
  )::numeric(7,2) as hours_left,
  f.active
from public.families f
join public.schools s on s.id = f.school_id
left join public.service_entries se on se.family_record_id = f.id
group by
  f.id, f.school_id, s.school_name, f.family_id,
  f.student_name, f.grade, f.required_hours, f.active;

grant select on public.family_hour_progress to authenticated;

-- -----------------------------
-- SAMPLE SCHOOL INSERT
-- Replace or add your complete school list.
-- -----------------------------
insert into public.schools (school_name)
values
  ('Barnum School'),
  ('Batalla School'),
  ('Beardsley School'),
  ('Black Rock School'),
  ('Blackham School'),
  ('Bryant School'),
  ('Central High School'),
  ('Harding High School'),
  ('Bassick High School')
on conflict (school_name) do nothing;

-- -----------------------------
-- MAKE A SPECIFIC USER AN ADMIN
-- Change the email if needed.
-- -----------------------------
update public.profiles
set role = 'admin'
where lower(email) = lower('pkaraffa@bridgeportedu.net');
